[workspace]
authors = ["kalin chakma <chakma.kalin10211@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "nnfs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.4.0.dev2025052817,<26"
